/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface IncidentUpdate {
    message: string;
    timestamp: Time;
}
export type Time = bigint;
export interface IncidentDTO {
    id: string;
    status: Status;
    title: string;
    affectedService: string;
    createdAt: Time;
    description: string;
    updatedAt: Time;
    updates: Array<IncidentUpdate>;
    severity: Severity;
}
export enum Severity {
    major = "major",
    minor = "minor",
    critical = "critical",
    informational = "informational"
}
export enum Status {
    resolved = "resolved",
    investigating = "investigating",
    monitoring = "monitoring",
    identified = "identified"
}
export interface backendInterface {
    addUpdate(incidentId: string, title: string, description: string, affectedService: string, severity: Severity, message: string): Promise<IncidentDTO>;
    changeStatus(incidentId: string, title: string, description: string, affectedService: string, severity: Severity, newStatus: string): Promise<IncidentDTO>;
    createIncident(id: string, title: string, description: string, affectedService: string, severity: Severity): Promise<IncidentDTO>;
    getAllIncidents(): Promise<Array<IncidentDTO>>;
    getIncident(incidentId: string): Promise<IncidentDTO | null>;
    isIdAlreadyUsed(id: string): Promise<boolean>;
}
import type { IncidentDTO as _IncidentDTO, IncidentUpdate as _IncidentUpdate, Severity as _Severity, Status as _Status, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addUpdate(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Severity, arg5: string): Promise<IncidentDTO> {
        if (this.processError) {
            try {
                const result = await this.actor.addUpdate(arg0, arg1, arg2, arg3, to_candid_Severity_n1(this._uploadFile, this._downloadFile, arg4), arg5);
                return from_candid_IncidentDTO_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addUpdate(arg0, arg1, arg2, arg3, to_candid_Severity_n1(this._uploadFile, this._downloadFile, arg4), arg5);
            return from_candid_IncidentDTO_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async changeStatus(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Severity, arg5: string): Promise<IncidentDTO> {
        if (this.processError) {
            try {
                const result = await this.actor.changeStatus(arg0, arg1, arg2, arg3, to_candid_Severity_n1(this._uploadFile, this._downloadFile, arg4), arg5);
                return from_candid_IncidentDTO_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changeStatus(arg0, arg1, arg2, arg3, to_candid_Severity_n1(this._uploadFile, this._downloadFile, arg4), arg5);
            return from_candid_IncidentDTO_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async createIncident(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Severity): Promise<IncidentDTO> {
        if (this.processError) {
            try {
                const result = await this.actor.createIncident(arg0, arg1, arg2, arg3, to_candid_Severity_n1(this._uploadFile, this._downloadFile, arg4));
                return from_candid_IncidentDTO_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createIncident(arg0, arg1, arg2, arg3, to_candid_Severity_n1(this._uploadFile, this._downloadFile, arg4));
            return from_candid_IncidentDTO_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllIncidents(): Promise<Array<IncidentDTO>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllIncidents();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllIncidents();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIncident(arg0: string): Promise<IncidentDTO | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncident(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncident(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async isIdAlreadyUsed(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isIdAlreadyUsed(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isIdAlreadyUsed(arg0);
            return result;
        }
    }
}
function from_candid_IncidentDTO_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IncidentDTO): IncidentDTO {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Severity_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Severity): Severity {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_IncidentDTO]): IncidentDTO | null {
    return value.length === 0 ? null : from_candid_IncidentDTO_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _Status;
    title: string;
    affectedService: string;
    createdAt: _Time;
    description: string;
    updatedAt: _Time;
    updates: Array<_IncidentUpdate>;
    severity: _Severity;
}): {
    id: string;
    status: Status;
    title: string;
    affectedService: string;
    createdAt: Time;
    description: string;
    updatedAt: Time;
    updates: Array<IncidentUpdate>;
    severity: Severity;
} {
    return {
        id: value.id,
        status: from_candid_Status_n5(_uploadFile, _downloadFile, value.status),
        title: value.title,
        affectedService: value.affectedService,
        createdAt: value.createdAt,
        description: value.description,
        updatedAt: value.updatedAt,
        updates: value.updates,
        severity: from_candid_Severity_n7(_uploadFile, _downloadFile, value.severity)
    };
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resolved: null;
} | {
    investigating: null;
} | {
    monitoring: null;
} | {
    identified: null;
}): Status {
    return "resolved" in value ? Status.resolved : "investigating" in value ? Status.investigating : "monitoring" in value ? Status.monitoring : "identified" in value ? Status.identified : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    major: null;
} | {
    minor: null;
} | {
    critical: null;
} | {
    informational: null;
}): Severity {
    return "major" in value ? Severity.major : "minor" in value ? Severity.minor : "critical" in value ? Severity.critical : "informational" in value ? Severity.informational : value;
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_IncidentDTO>): Array<IncidentDTO> {
    return value.map((x)=>from_candid_IncidentDTO_n3(_uploadFile, _downloadFile, x));
}
function to_candid_Severity_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Severity): _Severity {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Severity): {
    major: null;
} | {
    minor: null;
} | {
    critical: null;
} | {
    informational: null;
} {
    return value == Severity.major ? {
        major: null
    } : value == Severity.minor ? {
        minor: null
    } : value == Severity.critical ? {
        critical: null
    } : value == Severity.informational ? {
        informational: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
