/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface IncidentDTO {
  'id' : string,
  'status' : Status,
  'title' : string,
  'affectedService' : string,
  'createdAt' : Time,
  'description' : string,
  'updatedAt' : Time,
  'updates' : Array<IncidentUpdate>,
  'severity' : Severity,
}
export interface IncidentUpdate { 'message' : string, 'timestamp' : Time }
export type Severity = { 'major' : null } |
  { 'minor' : null } |
  { 'critical' : null } |
  { 'informational' : null };
export type Status = { 'resolved' : null } |
  { 'investigating' : null } |
  { 'monitoring' : null } |
  { 'identified' : null };
export type Time = bigint;
export interface _SERVICE {
  'addUpdate' : ActorMethod<
    [string, string, string, string, Severity, string],
    IncidentDTO
  >,
  'changeStatus' : ActorMethod<
    [string, string, string, string, Severity, string],
    IncidentDTO
  >,
  'createIncident' : ActorMethod<
    [string, string, string, string, Severity],
    IncidentDTO
  >,
  'getAllIncidents' : ActorMethod<[], Array<IncidentDTO>>,
  'getIncident' : ActorMethod<[string], [] | [IncidentDTO]>,
  'isIdAlreadyUsed' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];