/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Severity = IDL.Variant({
  'major' : IDL.Null,
  'minor' : IDL.Null,
  'critical' : IDL.Null,
  'informational' : IDL.Null,
});
export const Status = IDL.Variant({
  'resolved' : IDL.Null,
  'investigating' : IDL.Null,
  'monitoring' : IDL.Null,
  'identified' : IDL.Null,
});
export const Time = IDL.Int;
export const IncidentUpdate = IDL.Record({
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const IncidentDTO = IDL.Record({
  'id' : IDL.Text,
  'status' : Status,
  'title' : IDL.Text,
  'affectedService' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'updatedAt' : Time,
  'updates' : IDL.Vec(IncidentUpdate),
  'severity' : Severity,
});

export const idlService = IDL.Service({
  'addUpdate' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Severity, IDL.Text],
      [IncidentDTO],
      [],
    ),
  'changeStatus' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Severity, IDL.Text],
      [IncidentDTO],
      [],
    ),
  'createIncident' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Severity],
      [IncidentDTO],
      [],
    ),
  'getAllIncidents' : IDL.Func([], [IDL.Vec(IncidentDTO)], ['query']),
  'getIncident' : IDL.Func([IDL.Text], [IDL.Opt(IncidentDTO)], ['query']),
  'isIdAlreadyUsed' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Severity = IDL.Variant({
    'major' : IDL.Null,
    'minor' : IDL.Null,
    'critical' : IDL.Null,
    'informational' : IDL.Null,
  });
  const Status = IDL.Variant({
    'resolved' : IDL.Null,
    'investigating' : IDL.Null,
    'monitoring' : IDL.Null,
    'identified' : IDL.Null,
  });
  const Time = IDL.Int;
  const IncidentUpdate = IDL.Record({
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const IncidentDTO = IDL.Record({
    'id' : IDL.Text,
    'status' : Status,
    'title' : IDL.Text,
    'affectedService' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'updatedAt' : Time,
    'updates' : IDL.Vec(IncidentUpdate),
    'severity' : Severity,
  });
  
  return IDL.Service({
    'addUpdate' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Severity, IDL.Text],
        [IncidentDTO],
        [],
      ),
    'changeStatus' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Severity, IDL.Text],
        [IncidentDTO],
        [],
      ),
    'createIncident' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Severity],
        [IncidentDTO],
        [],
      ),
    'getAllIncidents' : IDL.Func([], [IDL.Vec(IncidentDTO)], ['query']),
    'getIncident' : IDL.Func([IDL.Text], [IDL.Opt(IncidentDTO)], ['query']),
    'isIdAlreadyUsed' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };